"""analytics page views for visitor charts

Revision ID: 0006
Revises: 0005
Create Date: 2026-03-28
"""

from alembic import op

revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS analytics_page_views (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            path VARCHAR(500) NOT NULL,
            session_id VARCHAR(64) NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        );
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_analytics_page_views_created_at ON analytics_page_views(created_at);")
    op.execute("CREATE INDEX IF NOT EXISTS ix_analytics_page_views_path ON analytics_page_views(path);")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS analytics_page_views;")
